#!/usr/bin/bash

USER_BINDIR=$HOME/.local/bin
ZSHPATH=$HOME/.zsh

link () {
    from=$1
    todir=$2
    frompath=$(realpath "$from")
    topath=$todir/$(basename "${from}")
    resolved="$(readlink "$topath")"
    if [[ ! $frompath == "$resolved" ]]; then
        ln -s -b "$frompath" "$todir"
    fi
}

link_homeroot () {
    LINKS=(
        "vimrc $HOME/.vim"
        ".Xresources $HOME"
        ".gitconfig $HOME"
        ".gitignore $HOME"
        ".tmux.conf $HOME"
    )
    for link_pair in "${LINKS[@]}"; do
        link $link_pair
    done

}

link_bindir () {
    scripts="$(fd -a . bin)"

    for script in $scripts; do
        link "$script" "$USER_BINDIR"
    done
}
link_zsh () {
    for file in $(fd ".z" .zsh/ -aHd1); do
        link "$file" "$ZSHPATH"
    done
}

link_homeroot
link_bindir
link_zsh
