#!/usr/bin/env bash

# linuxbrew
function install_linuxbrew () {
    git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
    mkdir -p ~/.linuxbrew/bin
    ln -is ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
    eval $(~/.linuxbrew/bin/brew shellenv)
}

function pre_setup () {
    brew install bitwarden-cli
}

function link_configs () {
    [[ -z $DF ]] && echo "ERROR: export DF=<dotfiles directory>" && exit 1

    ln -is "$DF/.tmux.conf" ~
    ln -is "$DF/.gitconfig" ~
    ln -is "$DF/.gitignore" ~
    ln -is "$DF/.zshenv" ~

    link_zsh=(
        .zshrc
        git_aliases
        functions
        aliases
        sens
        fzf
    )

    [[ ! -d ~/.zsh ]] && mkdir ~/.zsh
    for name in "${link_zsh[@]}"; do
        ln -is "$DF/.zsh/$name" ~/.zsh
    done
}

#
#
#
# # apt
# apt update
# apt install tmux luarocks qutebrowser copyq fonts-ibm-plex conky vim
#
# # luarocks
# luarocks install luacheck
#
# brew install gh pyenv pipx bat fd glow pandoc
#
# # github
# # git-extras
#
# # pipx - Python standalone packages
# pyenv install 3.6.12
# pyenv global 3.6.12
#
# pkgs='''
# beets==1.4.9
# black==20.8b1
# dephell==0.8.3
# flake8==3.8.3
# grip==4.5.2
# howdoi==2.0.7
# mypy==0.782
# poetry==1.10.0
# pylint==2.6.0
# pytest==6.0.2
# restview==2.9.2
# s-tui==1.0.2
# twine==3.2.0
# yamllint==1.24.2
# bitwarden-keyring'''
#
# for a in $(zsh pipx_dump.txt); do pipx install $a; done
# pipx inject black isort --include-apps
#
# # Go - Jira and mark
# export $GOPATH=$HOME/.local/go/bin
#
# # go-jira/jira
# # kovetskiy/mark
# # sachaos/todoist
#
# # vim:ft=bash
